kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "rag.fullname" . }}
  labels:
    {{- include "rag.labels" . | nindent 4 }}
  annotations:
    # 10 minute timeout for large document uploads
    haproxy.router.openshift.io/timeout: 600s
spec:
  to:
    kind: Service
    name: {{ include "rag.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  alternateBackends: []
